// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC-GvEC_2xKjnBDZVoC-bOkNaeVVvMWQE',
    appId: '1:352366066969:web:3ea8f043d1db09c964d988',
    messagingSenderId: '352366066969',
    projectId: 'smetchikapp',
    authDomain: 'smetchikapp.firebaseapp.com',
    storageBucket: 'smetchikapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBib09IxPflD4dr2z6fxTs-Rci7Y_AxTaY',
    appId: '1:352366066969:android:9153f0d6ad172db364d988',
    messagingSenderId: '352366066969',
    projectId: 'smetchikapp',
    storageBucket: 'smetchikapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZIyovFHK7zhC9F1crqv9wzBJ9-8cUuuk',
    appId: '1:352366066969:ios:68937aca039065f064d988',
    messagingSenderId: '352366066969',
    projectId: 'smetchikapp',
    storageBucket: 'smetchikapp.firebasestorage.app',
    iosBundleId: 'com.example.newProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZIyovFHK7zhC9F1crqv9wzBJ9-8cUuuk',
    appId: '1:352366066969:ios:68937aca039065f064d988',
    messagingSenderId: '352366066969',
    projectId: 'smetchikapp',
    storageBucket: 'smetchikapp.firebasestorage.app',
    iosBundleId: 'com.example.newProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDC-GvEC_2xKjnBDZVoC-bOkNaeVVvMWQE',
    appId: '1:352366066969:web:48746c48fdeb647464d988',
    messagingSenderId: '352366066969',
    projectId: 'smetchikapp',
    authDomain: 'smetchikapp.firebaseapp.com',
    storageBucket: 'smetchikapp.firebasestorage.app',
  );

}